sonar.projectKey=helmuth6553-dotcom_WoBePlaner
sonar.organization=helmuth6553-dotcom
sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,scripts/**,sql_archive/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
